# Generated by Django 3.1.5 on 2021-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_auto_20210226_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='team_title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
