# Generated by Django 3.1.5 on 2021-02-23 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210219_1649'),
        ('accounts', '0002_auto_20210220_1610'),
    ]

    operations = [
    ]
