# Generated by Django 3.1.5 on 2021-03-02 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210225_1847'),
        ('accounts', '0002_profile_resume'),
    ]

    operations = [
    ]
