# Generated by Django 3.1.5 on 2021-03-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210308_1319'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='profile',
    #         name='image',
    #     ),
    # ]
