# Generated by Django 3.1.5 on 2021-03-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_profile_programming_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_sponsors_see',
            field=models.BooleanField(default=True),
        ),
    ]
