# Generated by Django 3.1.5 on 2021-03-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_profile_can_sponsors_see'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('java', 'Java'), ('py3', 'Python 3')], max_length=32, null=True),
        ),
    ]
