# Generated by Django 3.1.5 on 2021-03-13 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20210312_0937'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=1024)),
                ('expires_at', models.PositiveBigIntegerField()),
                ('expires_in', models.PositiveIntegerField()),
                ('id_token', models.TextField()),
                ('scope', models.TextField()),
            ],
        ),
    ]
