# Generated by Django 3.1.5 on 2021-03-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_googlelogin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobexperience',
            name='company',
            field=models.CharField(blank=True, default='_', max_length=128, null=True),
        ),
    ]
