# Generated by Django 3.1.5 on 2021-03-16 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210316_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='university_degree',
            field=models.CharField(blank=True, choices=[('ST', 'دانش\u200c آموز'), ('BA', 'کارشناسی'), ('MA', 'کارشناسی ارشد'), ('DO', 'دکترا')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='university_term',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
