# Generated by Django 3.1.5 on 2021-03-16 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_universityapiconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universityapiconfig',
            name='headers',
            field=models.TextField(),
        ),
    ]
