# Generated by Django 3.1.5 on 2021-03-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_major'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlelogin',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='googlelogin',
            name='is_signup',
            field=models.BooleanField(default=False),
        ),
    ]
