# Generated by Django 3.1.5 on 2021-04-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_auto_20210320_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='programming_language',
            field=models.CharField(blank=True, choices=[('cpp', 'C++'), ('java', 'Java'), ('py3', 'Python 3'), ('jar', 'Jar')], max_length=32, null=True),
        ),
    ]
