# Generated by Django 3.1.5 on 2021-02-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_quote_sponsor_whythisevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Motto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motto', models.CharField(max_length=128)),
                ('pre_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('url', models.URLField(max_length=256)),
                ('icon', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='prize',
            name='team_name',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
    ]