# Generated by Django 3.1.5 on 2021-02-23 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20210222_1552'),
        ('homepage', '0006_rule'),
    ]

    operations = [
    ]
