# Generated by Django 3.1.5 on 2021-02-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_merge_20210223_2005'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Stats',
        ),
    ]
