# Generated by Django 3.1.5 on 2021-02-24 14:47

import apps.homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20210223_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='icon',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.FileField(upload_to=apps.homepage.models.Sponsor.upload_path),
        ),
    ]
