# Generated by Django 3.1.5 on 2021-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20210224_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelineevent',
            name='day',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='timelineevent',
            name='month',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
