# Generated by Django 3.1.5 on 2021-02-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAddEventToCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
            ],
        ),
    ]
