# Generated by Django 3.1.5 on 2021-02-28 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_googleaddeventtocalender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motto',
            name='pre_text',
            field=models.CharField(max_length=2048),
        ),
    ]
