# Generated by Django 3.1.5 on 2021-02-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20210228_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='motto',
            name='motto',
            field=models.CharField(max_length=2048),
        ),
    ]
