# Generated by Django 3.1.5 on 2021-04-05 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_auto_20210228_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sponsor',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='name_fa',
        ),
        migrations.CreateModel(
            name='SponsorSocialMedia',
            fields=[
                ('socialmedia_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='homepage.socialmedia')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='homepage.sponsor')),
            ],
            bases=('homepage.socialmedia',),
        ),
    ]
