# Generated by Django 3.1.5 on 2021-04-05 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_auto_20210405_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SponsorJobOpportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_url', models.URLField(help_text='Job opp url at sponsor website', max_length=512)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='homepage.sponsor')),
            ],
        ),
    ]
