# Generated by Django 3.1.5 on 2021-04-05 10:17

import apps.homepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20210405_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=apps.homepage.models.Sponsor.upload_path),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=apps.homepage.models.Sponsor.upload_path),
        ),
    ]
