# Generated by Django 3.1.5 on 2021-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_auto_20210405_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorjobopportunity',
            name='title',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
