# Generated by Django 3.1.5 on 2021-04-05 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_sponsorjobopportunity_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='title',
            new_name='title_fa',
        ),
    ]
