# Generated by Django 3.1.5 on 2021-04-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20210405_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='title_en',
            field=models.CharField(default='', max_length=512, unique=True),
            preserve_default=False,
        ),
    ]
