# Generated by Django 3.1.5 on 2021-04-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20210405_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='title_en',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='title_fa',
            field=models.CharField(max_length=512, null=True, unique=True),
        ),
    ]
