# Generated by Django 3.1.5 on 2021-03-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='html',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='html',
        ),
    ]
