# Generated by Django 3.1.5 on 2021-04-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20210320_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='text',
            field=models.TextField(),
        ),
    ]
