# Generated by Django 3.1.5 on 2021-04-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infra_gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infraeventpush',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(100, 100), (102, 102), (402, 402), (404, 404), (500, 500), (502, 502), (504, 504), (506, 506)], default=200),
        ),
    ]
