# Generated by Django 3.1.5 on 2021-03-23 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0011_auto_20201117_2016'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequestLogProxy',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rest_framework_tracking.apirequestlog',),
        ),
    ]
