# Generated by Django 3.1.5 on 2021-03-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_aparatmedia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparatmedia',
            name='script',
        ),
    ]
