# Generated by Django 3.1.5 on 2021-03-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_aparatmedia_script'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparatmedia',
            name='aparat_id',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aparatmedia',
            name='aparat_src',
            field=models.URLField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
