# Generated by Django 3.1.5 on 2021-03-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210306_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='google_calendar_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='webinar_link',
            field=models.URLField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_en',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='title_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
