# Generated by Django 3.1.5 on 2021-03-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210308_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_webinar',
            field=models.BooleanField(default=False),
        ),
    ]
