# Generated by Django 3.1.5 on 2021-02-20 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='source',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='target',
        ),
        migrations.AddField(
            model_name='invitation',
            name='source_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='team.team'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='target_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='team.team'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
