# Generated by Django 3.1.5 on 2021-02-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210220_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='source_team',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='target_team',
        ),
        migrations.AddField(
            model_name='invitation',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='team.team'),
            preserve_default=False,
        ),
    ]
