# Generated by Django 3.1.5 on 2021-02-21 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_auto_20210220_1923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='target_user',
        ),
        migrations.AddField(
            model_name='invitation',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='accounts.user'),
            preserve_default=False,
        ),
    ]
