# Generated by Django 3.1.5 on 2021-03-23 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210225_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='level_one_payed',
            field=models.BooleanField(default=False),
        ),
    ]
