# Generated by Django 3.1.5 on 2021-04-09 19:18

import apps.team.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_auto_20210329_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=apps.team.models.get_submission_file_directory),
        ),
    ]
