# Generated by Django 3.1.5 on 2021-04-10 17:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20210409_1918'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('humans', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='is_bot',
            field=models.BooleanField(default=False),
        ),
    ]
