# Generated by Django 3.1.5 on 2021-04-10 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0011_auto_20210410_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='bot_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
