# Generated by Django 3.1.5 on 2021-04-11 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_team_bot_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='team',
            managers=[
            ],
        ),
    ]
