# Generated by Django 3.1.5 on 2021-04-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20210425_0813'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_mini_game',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_mini_game_final',
            field=models.BooleanField(default=False),
        ),
    ]
