# Generated by Django 3.1.5 on 2021-02-25 07:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20210221_2218'),
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('accepted', 'Accepted')], default='pending', max_length=50)),
                ('type', models.CharField(choices=[('friendly_match', 'Friendly match'), ('clan_invite', 'Clan invite'), ('clanwar', 'Clanwar')], max_length=50)),
                ('source_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='team.team')),
                ('target_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_request', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
