# Generated by Django 3.1.5 on 2021-03-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='infra_token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
