# Generated by Django 3.1.5 on 2021-02-25 08:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210225_0740'),
        ('challenge', '0002_request'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='matchinfo',
        #     name='match_duration',
        #     field=models.PositiveSmallIntegerField(),
        # ),
        migrations.CreateModel(
            name='Clan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='clan/images/')),
                ('score', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='owned_clan', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
