# Generated by Django 3.1.5 on 2021-02-25 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210225_0740'),
        ('challenge', '0003_auto_20210225_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClanTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clan', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to='team.team')),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenge.clan')),
            ],
        ),
    ]
