# Generated by Django 3.1.5 on 2021-02-25 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0004_clanteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clanwar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('clan1', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clanwars1', to='challenge.clan')),
                ('clan2', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clanwars2', to='challenge.clan')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clanwar', to='challenge.tournament')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
