# Generated by Django 3.1.5 on 2021-02-25 08:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210225_0740'),
        ('challenge', '0005_clanwar'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyQueue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('game_type', models.CharField(choices=[('friendly_match', 'Friendly match'), ('level_based_tournament', 'Level based tournament')], default='friendly_match', max_length=50)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_queue', to='team.team')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
