# Generated by Django 3.1.5 on 2021-03-29 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0008_auto_20210329_0759'),
        ('challenge', '0006_auto_20210329_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboardrow',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scoreboard_rows', to='team.team'),
        ),
    ]
