# Generated by Django 3.1.5 on 2021-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0007_auto_20210329_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboardrow',
            name='score',
            field=models.PositiveIntegerField(default=1000),
        ),
    ]
