# Generated by Django 3.1.5 on 2021-04-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_auto_20210329_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('friendly', 'Friendly'), ('clanwar', 'Clanwar'), ('bot', 'Bot')], default='normal', max_length=50),
        ),
    ]
