# Generated by Django 3.1.5 on 2021-02-25 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0008_levelbasedtournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('level_based_tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level', to='challenge.levelbasedtournament')),
            ],
        ),
    ]
