# Generated by Django 3.1.5 on 2021-04-15 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_auto_20210410_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_name', models.CharField(max_length=512)),
                ('start_time', models.DateTimeField()),
                ('match_map', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='leagues', to='challenge.map')),
            ],
        ),
    ]
