# Generated by Django 3.1.5 on 2021-02-25 08:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0009_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelMatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_matches', to='challenge.level')),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='level_match', to='challenge.match')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
