# Generated by Django 3.1.5 on 2021-02-25 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210225_0740'),
        ('challenge', '0010_levelmatch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='is_freeze',
        ),
        migrations.AlterField(
            model_name='lobbyqueue',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_queues', to='team.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('failed', 'Failed'), ('successful', 'Successful'), ('running', 'Running'), ('freeze', 'Freeze')], default='running', max_length=50),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='won_matches', to='team.team'),
        ),
    ]
