# Generated by Django 3.1.5 on 2021-04-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0010_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='total_matches',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
