# Generated by Django 3.1.5 on 2021-03-11 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20210225_0740'),
        ('challenge', '0011_auto_20210225_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='types',
            new_name='type',
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team1_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_first', to='team.submission'),
        ),
        migrations.AddField(
            model_name='matchinfo',
            name='team2_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_second', to='team.submission'),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='match_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='team1_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchinfo',
            name='team2_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
