# Generated by Django 3.1.5 on 2021-03-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0011_auto_20210225_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
