# Generated by Django 3.1.5 on 2021-03-18 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0012_auto_20210311_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='level_based_tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='challenge.levelbasedtournament'),
        ),
        migrations.AlterField(
            model_name='level',
            name='number',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
