# Generated by Django 3.1.5 on 2021-04-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0013_league_two_way'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('friendly', 'Friendly'), ('clanwar', 'Clanwar'), ('bot', 'Bot'), ('final', 'Final')], default='normal', max_length=50),
        ),
    ]
