# Generated by Django 3.1.5 on 2021-03-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_auto_20210323_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinfo',
            name='match_duration',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
