# Generated by Django 3.1.5 on 2021-04-24 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0014_auto_20210424_0805'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergeScoreboards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dest_merges', to='challenge.tournament')),
                ('src', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='src_merges', to='challenge.tournament')),
            ],
        ),
    ]
