# Generated by Django 3.1.5 on 2021-04-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0016_auto_20210424_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
