# Generated by Django 3.1.5 on 2021-02-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Past',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('title_en', models.CharField(max_length=50, blank=True)),
                ('title_fa', models.CharField(max_length=50)),
                ('description_en', models.TextField(max_length=1000, blank=True)),
                ('description_fa', models.TextField(max_length=1000)),
                ('firstTeam', models.TextField(max_length=50)),
                ('secondTeam', models.TextField(max_length=50)),
                ('thirdTeam', models.TextField(max_length=50)),
            ],
        ),
    ]
