# Generated by Django 3.1.5 on 2021-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=50, blank=True)),
                ('title_fa', models.CharField(max_length=50)),
                ('text_en', models.TextField(max_length=10000, blank=True)),
                ('text_fa', models.TextField(max_length=10000)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
